theme: jekyll-theme-minimal

gems:
  - jekyll-seo-tag

title: QuicKey – The quick tab switcher

description: A Chrome extension that lets you quickly switch tabs or access bookmarks and history via a Quicksilver-style search.

tagline: Quickly switch tabs or access bookmarks and history with a Quicksilver-style search.

image: /img/search-box-open.png

logo: /img/icon-300.png

google_analytics: UA-3380390-2

twitter:
  username: fwextensions
  creator: fwextensions

author: John Dunning
