gems:
  - jekyll-seo-tag
theme: jekyll-theme-minimal
title: QuicKey
description: A Chrome extension for switching tabs or pulling up bookmarks and history via a Quicksilver-style search.
logo: img/icon-128.png
twitter:
  username: fwextensions
author: John Dunning
