theme: jekyll-theme-minimal

gems:
  - jekyll-seo-tag

title: QuicKey

description: A Chrome extension for switching tabs or pulling up bookmarks and history via a Quicksilver-style search.

image: /img/search-box-open.png

google_analytics: UA-3380390-2

twitter:
  username: fwextensions
  creator: fwextensions

author: John Dunning
