theme: jekyll-theme-minimal

gems:
  - jekyll-seo-tag

title: QuicKey

description: A Chrome extension for switching tabs or pulling up bookmarks and history via a Quicksilver-style search.

logo: img/icon-128.png

image: img/search-box-open.png

url: https://chrome.google.com/webstore/

twitter:
  username: fwextensions
  creator: fwextensions

author: John Dunning
